INFO:root:GET request method 

INFO:root:response :  

INFO:root:{'results': [{'name': 'fidelius', 'stars': 11}, {'name': 'nsync', 'stars': 7}, {'name': 'webpush', 'stars': 0}], 'response_time_from_git': 2.129725, 'total_time': 2.1552462577819824}
INFO:root:POST request method 

INFO:root:response :  

INFO:root:{'results': [{'name': 'fidelius', 'stars': 11}, {'name': 'nsync', 'stars': 7}, {'name': 'webpush', 'stars': 0}]}
INFO:root:GET request method 

INFO:root:response :  

INFO:root:{'results': [{'name': 'fidelius', 'stars': 11}, {'name': 'nsync', 'stars': 7}, {'name': 'webpush', 'stars': 0}], 'response_time_from_git': 1.25802, 'total_time': 1.2885572910308838}
ERROR:django.request:Internal Server Error: /api/one/
Traceback (most recent call last):
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 457, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 468, in raise_uncaught_exception
    raise exc
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 494, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "H:\sem7\asgn1\createAPI\views.py", line 80, in github
    return render(request, 'createAPI/github.html', {'user': user})
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\loader_tags.py", line 53, in render
    result = self.nodelist.render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\defaulttags.py", line 200, in render
    .format(num_loopvars, len_item),
ValueError: Need 2 values to unpack in for loop; got 7. 
INFO:root:GET request method 

INFO:root:response :  

INFO:root:{'results': [{'name': 'fidelius', 'stars': 11}, {'name': 'nsync', 'stars': 7}, {'name': 'webpush', 'stars': 0}], 'response_time_from_git': 1.281866, 'total_time': 1.3124926090240479}
ERROR:django.request:Internal Server Error: /api/one/
Traceback (most recent call last):
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 457, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 468, in raise_uncaught_exception
    raise exc
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 494, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "H:\sem7\asgn1\createAPI\views.py", line 80, in github
    return render(request, 'createAPI/github.html', {'user': user})
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\loader_tags.py", line 53, in render
    result = self.nodelist.render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\defaulttags.py", line 200, in render
    .format(num_loopvars, len_item),
ValueError: Need 2 values to unpack in for loop; got 7. 
INFO:root:GET request method 

INFO:root:response :  

INFO:root:{'total_time': 2.13346529006958, 'response_time_from_git': 2.110418, 'results': [{'name': 'fidelius', 'stars': 11}, {'name': 'nsync', 'stars': 7}, {'name': 'webpush', 'stars': 0}]}
ERROR:django.request:Internal Server Error: /api/one/
Traceback (most recent call last):
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 457, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 468, in raise_uncaught_exception
    raise exc
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 494, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "H:\sem7\asgn1\createAPI\views.py", line 80, in github
    return render(request, 'createAPI/github.html', {'user': user})
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\loader_tags.py", line 53, in render
    result = self.nodelist.render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\defaulttags.py", line 200, in render
    .format(num_loopvars, len_item),
ValueError: Need 2 values to unpack in for loop; got 10. 
INFO:root:GET request method 

INFO:root:response :  

INFO:root:{'total_time': 1.9391977787017822, 'response_time_from_git': 1.913458, 'results': [{'name': 'fidelius', 'stars': 11}, {'name': 'nsync', 'stars': 7}, {'name': 'webpush', 'stars': 0}]}
INFO:root:GET request method 

INFO:root:response :  

INFO:root:{'total_time': 1.495222568511963, 'response_time_from_git': 1.470107, 'results': [{'name': 'fidelius', 'stars': 11}, {'name': 'nsync', 'stars': 7}, {'name': 'webpush', 'stars': 0}]}
ERROR:django.request:Internal Server Error: /api/one/
Traceback (most recent call last):
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 457, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 468, in raise_uncaught_exception
    raise exc
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 494, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "H:\sem7\asgn1\createAPI\views.py", line 80, in github
    return render(request, 'createAPI/github.html', {'user': user})
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\loader_tags.py", line 53, in render
    result = self.nodelist.render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\defaulttags.py", line 200, in render
    .format(num_loopvars, len_item),
ValueError: Need 2 values to unpack in for loop; got 10. 
INFO:root:GET request method 

INFO:root:response :  

INFO:root:{'total_time': 1.1201400756835938, 'response_time_from_git': 1.092535, 'results': [{'name': 'fidelius', 'stars': 11}, {'name': 'nsync', 'stars': 7}, {'name': 'webpush', 'stars': 0}]}
ERROR:django.request:Internal Server Error: /api/one/
Traceback (most recent call last):
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 457, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 468, in raise_uncaught_exception
    raise exc
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 494, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "H:\sem7\asgn1\createAPI\views.py", line 80, in github
    return render(request, 'createAPI/github.html', {'user': user})
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\defaulttags.py", line 811, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[i]' from 'user[i]'
INFO:root:GET request method 

INFO:root:response :  

INFO:root:{'total_time': 1.4965457916259766, 'response_time_from_git': 1.474789, 'results': [{'name': 'fidelius', 'stars': 11}, {'name': 'nsync', 'stars': 7}, {'name': 'webpush', 'stars': 0}]}
ERROR:django.request:Internal Server Error: /api/one/
Traceback (most recent call last):
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 457, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 468, in raise_uncaught_exception
    raise exc
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\views.py", line 494, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "H:\sem7\asgn1\createAPI\views.py", line 80, in github
    return render(request, 'createAPI/github.html', {'user': user})
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\defaulttags.py", line 811, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\Vaishnavi\AppData\Local\Programs\Python\Python35\lib\site-packages\django\template\base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[i]' from 'user[i]'
INFO:root:GET request method 

INFO:root:response :  

INFO:root:{'total_time': 1.6108553409576416, 'response_time_from_git': 1.59301, 'results': [{'name': 'fidelius', 'stars': 11}, {'name': 'nsync', 'stars': 7}, {'name': 'webpush', 'stars': 0}]}
INFO:root:GET request method 

INFO:root:response :  

INFO:root:{'total_time': 1.5678093433380127, 'response_time_from_git': 1.543185, 'results': [{'name': 'fidelius', 'stars': 11}, {'name': 'nsync', 'stars': 7}, {'name': 'webpush', 'stars': 0}]}
INFO:django.utils.autoreload:H:\sem7\asgn1\createAPI\views.py changed, reloading.
INFO:root:GET request method 

INFO:root:response :  

INFO:root:{'total_time': 2.551168441772461, 'results': [{'name': 'fidelius', 'stars': 11}, {'name': 'nsync', 'stars': 7}, {'name': 'webpush', 'stars': 0}], 'rate': {'remaining': '56', 'limit': '60'}, 'response_time_from_git': 2.525087}
INFO:root:GET request method 

INFO:root:response :  

INFO:root:{'total_time': 1.287841796875, 'results': [{'name': 'fidelius', 'stars': 11}, {'name': 'nsync', 'stars': 7}, {'name': 'webpush', 'stars': 0}], 'rate': {'remaining': '55', 'limit': '60'}, 'response_time_from_git': 1.255755}
INFO:root:GET request method 

INFO:root:response :  

INFO:root:{'total_time': 1.0080323219299316, 'results': [{'name': 'fidelius', 'stars': 11}, {'name': 'nsync', 'stars': 7}, {'name': 'webpush', 'stars': 0}], 'rate': {'remaining': '54', 'limit': '60'}, 'response_time_from_git': 0.975367}
